### ISSUE TITLE
RSS feed throws an Error display (Static Page)

### ISSUE THREAD

**Issue by Darwin1969** [Ayemae/Grawlix-Webcomic-CMS#12]
Hi there.  Me again.
I recently contacted you about a fix to the RSS feed and blank pages in a site I was building.  I followed your fix on Issue 7, and the fix you provided worked in getting the RSS feed and the blank pages to display.  I also need to add that I only fixed the broken lines and updated the database rather than uploading an entirely new set of files mid-build.

I just got a report from https://tuppenceforstardust.spiderforest.com (the site in question) that their RSS feed is now kicking back an error message (see the first image) rather than displaying the feed code like it did before.  When I look at the developer it shows that it is a static page error... but I'm not sure if that is "I throw an error through a static page" or that "I have a static page error."
![RSS error](https://user-images.githubusercontent.com/110792207/187006053-95eca012-71e8-4bbc-93bf-6bc99d502bd6.jpg)

Additionally when I try to get my reader to add https://tuppenceforstardust.spiderforest.com/rss?id=1 it tells me there is an error accessing the feed.

![feed reader error](https://user-images.githubusercontent.com/110792207/187006119-7d7b71e8-6ba0-451f-a117-c0a5a40ef339.jpg)

I caught sight of it only reading up to the /rss and not the ?id=1 part... (I can't remember what poke of the code showed me that though)

Any suggestions you can give me would be greatly appreciated.

**Comment by eishiya** [comment]
You're getting an invalid page because you're navigating to an invalid URL. The RSS feed is at `/comics/rss`, not just `/rss`.

https://tuppenceforstardust.spiderforest.com/comic/rss?id=1

**Comment by Darwin1969** [comment]
Oh my I totally missed that.  Thanks!
