### ISSUE TITLE
Clicking on "Edit book info" in Book View goes to a blank page

### ISSUE THREAD

**Issue by radiochio** [Ayemae/Grawlix-Webcomic-CMS#7]
I've been rebuilding my comic site using this version of Grawlix on MAMP locally, and everything seems to work ok. After uploading everything to my live site, suddenly the "Edit book info" link on the Book View page just goes to a blank page. It is a fresh install of Grawlix, so I'm not sure why it would just suddenly stop working correctly. Any suggestions or thoughts on why that might happen?

**Comment by darth-biomech** [comment]
I think I had something similar happen on my site once, and it turned out I uploaded stuff with a conversion of filenames to lower case.

**Comment by radiochio** [comment]
> I think I had something similar happen on my site once, and it turned out I uploaded stuff with a conversion of filenames to lower case.

Do you mean the filenames for the individual php files? I don't think I've ever had a version of them where those filenames were capitalized. I tried changing it just to see, and it didn't make a difference, still getting the blank white screen when I try to get to Edit Book Info.

**Comment by eishiya** [comment]
The PHP filenames for Grawlix are case-sensitive, and do include capital letters, e.g. `GrlxPage2.php` is not the same as `grlxpage2.php`.

**Comment by radiochio** [comment]
Ah yes, I wasn't thinking about those files, since I haven't touched any of them and forgot capitalized files do exist. 

But, yes, adding the ini_set line did help - I actually added it to book.edit.php and got an entire pageful of errors. This one is a little bit above my skill level, but here's what I've got:

`
Warning: simplexml_load_string(): Entity: line 2: parser error : StartTag: invalid element name in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): ><option>title</option><option>number</option></chapter></archive><rss><option>< in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): ^ in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): Entity: line 2: parser error : expected '>' in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): title</option><option>number</option></chapter></archive><rss><option><0>image</ in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): ^ in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): Entity: line 2: parser error : Opening and ending tag mismatch: option line 2 and unparseable in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): title</option><option>number</option></chapter></archive><rss><option><0>image</ in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): ^ in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): Entity: line 2: parser error : StartTag: invalid element name in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): le</option><option>number</option></chapter></archive><rss><option><0>image</0>< in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): ^ in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): Entity: line 2: parser error : expected '>' in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): ><option>number</option></chapter></archive><rss><option><0>image</0><1>number</ in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): ^ in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): Entity: line 2: parser error : Opening and ending tag mismatch: rss line 2 and unparseable in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): ><option>number</option></chapter></archive><rss><option><0>image</0><1>number</ in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): ^ in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): Entity: line 2: parser error : StartTag: invalid element name in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): ption>number</option></chapter></archive><rss><option><0>image</0><1>number</1>< in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): ^ in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): Entity: line 2: parser error : expected '>' in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): mber</option></chapter></archive><rss><option><0>image</0><1>number</1><2>blog</ in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): ^ in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): Entity: line 2: parser error : Opening and ending tag mismatch: book line 2 and unparseable in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): mber</option></chapter></archive><rss><option><0>image</0><1>number</1><2>blog</ in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): ^ in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): Entity: line 2: parser error : Extra content at the end of the document in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): mber</option></chapter></archive><rss><option><0>image</0><1>number</1><2>blog</ in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Warning: simplexml_load_string(): ^ in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 60

Fatal error: Uncaught Error: Call to a member function getName() on bool in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php:100 Stack trace: #0 /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php(30): GrlxXML->getInfo() #1 /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML_Book.php(56): GrlxXML->__construct() #2 /home/MYNAME/follower-comic.com/_admin/book.edit.php(117): GrlxXML_Book->__construct(Array) #3 {main} thrown in /home/MYNAME/follower-comic.com/_admin/lib/GrlxXML.php on line 100`

**Comment by eishiya** [comment]
Thanks, that at least provides a starting point. It looks like the XML that normally contains your book options is somehow busted. I wonder how that happened. Would you mind going into your database (e.g. via PHPMyAdmin, which most webhosts provide), into the grlx_book table, and pasting its full `options` field here?

Grawlix has checks to make sure it doesn't try to get data out of XML that couldn't be parsed (it should just display an error on the page), but it looks like they're not implemented quite right - Grawlix tries to do some work on the "parsed" XML before it checks that it's valid. That's easy enough to fix, at least.

**Comment by radiochio** [comment]
Thanks so much for your help, I really, really appreciate it!

Here's what's in the options field:

```
<?xml version="1.0" encoding="UTF-8"?>
<book version="1.1"><archive><behavior>single</behavior><page><layout>grid</layout><option>title</option><option>number</option><option>date</option></page><chapter><layout>list</layout><option>title</option><option>number</option></chapter></archive><rss><option><0>image</0><1>number</1><2>blog</2></option></rss></book>
```

**Comment by eishiya** [comment]
Ah, I see the problem, the RSS options have invalid tags:
```xml
<option><0>image</0><1>number</1><2>blog</2></option>
```
This was something that broke with PHP8, the way the SimpleXML object is handled is different.

This and many other PHP8-related issues are fixed on my fork: https://github.com/eishiya/Grawlix-Webcomic-CMS
It hasn't been merged into this repo yet because I haven't had opportunity to test certain features (such as multi-book and bulk uploads), but the parts I have checked all work fine. If you don't want to update your entire Grawlix, you can modify just `_admin/lib/GrlxXML_Book.php`, and if you don't want to update the entire file, you can change line 175 in `updateRSS()`,
replace:
```php
$this->simpleXML->rss->{$key}->{$key2} = $val2;
```
with:
```php
$this->simpleXML->rss->{$key}[$key2] = $val2;
```

Another alternative is to downgrade your PHP to 7.4, but not all hosts offer this as an option. And we could always use more people testing the PHP8 update before we merge it xP

Lastly, even if the code is fixed, you've already got a busted options XML that'll keep breaking things. You need to fix that. In your database, edit it to this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<book version="1.1"><archive><behavior>single</behavior><page><layout>grid</layout><option>title</option><option>number</option><option>date</option></page><chapter><layout>list</layout><option>title</option><option>number</option></chapter></archive><rss><option>image</option><option>number</option><option>blog</option></rss></book>
```

**Comment by radiochio** [comment]
Yeah, downgrading PHP was one of the first things I tried last night when I started on this, didn't seem to make a difference, so I went back to 8. 

In either case, I tried using your fork instead and (so far) it looks like everything's good! Database stuff is my personal nightmare, I never would have figured that out. Thank you so so much!

**Comment by eishiya** [comment]
Glad it works!

Let's leave this issue open since even though the problem fixed, the fix isn't in this repo yet.

**Comment by eishiya** [comment]
The update is now merged, so I'll close this issue.

**Comment by Darwin1969** [comment]
WHOOP!  

That worked for both the archive issue and the RSS issue!  Perfect!
Thank you for your help and your patience!  

I will pass this on to others in my group who are doing the same kinds of builds!

**Comment by Darwin1969** [comment]
That worked for both the archive issue and the RSS issue!  Perfect!
Thank you for your help and your patience!  

I will pass this on to others in my group who are doing the same kinds of builds!

**Comment by eishiya** [comment]
> I will pass this on to others in my group who are doing the same kinds of builds!

The update is now part of the main repo, so anyone getting the latest version from here starting today should be fine :D

**Comment by Darwin1969** [comment]
Very good, I will let them know that as well (I posted the fix above for people who may have already gotten started on them.)  I really appreciate your help on this!
